eureka:
  instance:
    hostname: ${EUREKA_URL:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
server:
  port: 8060

spring:
  application:
    name: cwbshop

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/cwbshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql: true
        id:
          new_generator_mappings: false
        search:
          autoregister_listeners: false
        bytecode:
          use_reflection_optimizer: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE